### 텐서 생성 및 변환


In [1]:
import torch

torch.tensor([[1, 2], [3, 4]])


/home/minhyuk/miniconda3/envs/pytorch/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[1, 2],
        [3, 4]])

In [2]:
tmp = torch.tensor([[1, 2], [3, 4]])
tmp.numpy()


array([[1, 2],
       [3, 4]])

In [3]:
tmp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
tmp.to("cpu").numpy()


array([[1, 2],
       [3, 4]])

In [4]:
print(torch.tensor([[1, 2], [3, 4]], dtype=float))
print(torch.FloatTensor([[1, 2], [3, 4]]))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.]])


### 텐서의 인덱스 조작


생략

### 텐서 연산

In [5]:
v1 = torch.tensor([3, 4, 7])
v2 = torch.tensor([1, 2, 3])
print("v1:", v1)
print("v2:", v2)
print("v1 + v2:", v1 + v2)
print("v1 - v2:", v1 - v2)
print("v1 * v2:", v1 * v2)
print("v1 / v2:", v1 / v2)
print("v1 % v2:", v1 % v2)

v1: tensor([3, 4, 7])
v2: tensor([1, 2, 3])
v1 + v2: tensor([ 4,  6, 10])
v1 - v2: tensor([2, 2, 4])
v1 * v2: tensor([ 3,  8, 21])
v1 / v2: tensor([3.0000, 2.0000, 2.3333])
v1 % v2: tensor([0, 0, 1])


### 텐서의 차원 조작
* view
  * 항상 원래 데이터를 가리킨다, copy 안 됨
* reshape
  * copy가 될 수도 있음
* transpose
  * 두 행을 교환, copy 안 됨
* permute
  * 원하는 행들을 교환, copy 안 됨

In [6]:
tmp = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("tmp.shape:", tmp.shape)
print(tmp.view(3,2))
print(tmp.view(-1))
print(tmp.view(1, -1))
tmp

tmp.shape: torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3, 4, 5, 6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

* ravel
  * copy가 안 된다.
* flatten
  * copy 된다.

In [9]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
print(a.flatten())

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])
