In [17]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))
print(preds)
print(target)
acc = torchmetrics.functional.accuracy(preds, target)
print((preds.argmax(dim=-1) == target).count_nonzero())
print(acc)

tensor([[0.2103, 0.0200, 0.1270, 0.1446, 0.4981],
        [0.1601, 0.3699, 0.1267, 0.1096, 0.2337],
        [0.1249, 0.1204, 0.1019, 0.1195, 0.5333],
        [0.1589, 0.3169, 0.0819, 0.0777, 0.3645],
        [0.0861, 0.0949, 0.3386, 0.0364, 0.4440],
        [0.0505, 0.3946, 0.2221, 0.2868, 0.0459],
        [0.4257, 0.0354, 0.0135, 0.2794, 0.2460],
        [0.2575, 0.0848, 0.0102, 0.5704, 0.0770],
        [0.6122, 0.1090, 0.0531, 0.1662, 0.0595],
        [0.0767, 0.1185, 0.2399, 0.4363, 0.1286]])
tensor([4, 3, 1, 1, 3, 0, 3, 3, 3, 4])
tensor(2)
tensor(0.2000)


In [16]:
metric = torchmetrics.Accuracy()

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))
acc = metric(preds, target)
print(preds)
print(target)
print((preds.argmax(dim=-1) == target).count_nonzero())
print(acc)

tensor([[0.1958, 0.2141, 0.0589, 0.4709, 0.0602],
        [0.0354, 0.3084, 0.2328, 0.1448, 0.2786],
        [0.0598, 0.6896, 0.0869, 0.1005, 0.0632],
        [0.0529, 0.0707, 0.5418, 0.2843, 0.0503],
        [0.0548, 0.0789, 0.0979, 0.7514, 0.0170],
        [0.0786, 0.5730, 0.0529, 0.0933, 0.2022],
        [0.0926, 0.2900, 0.2145, 0.1501, 0.2528],
        [0.0328, 0.0804, 0.4965, 0.2499, 0.1403],
        [0.0890, 0.0431, 0.4447, 0.3233, 0.0999],
        [0.3741, 0.2997, 0.1099, 0.1836, 0.0327]])
tensor([4, 2, 1, 1, 4, 0, 1, 0, 4, 0])
tensor(3)
tensor(0.3000)
