# ```tensor``` 탐구

## 생성

### `dypte`

In [156]:
import torch

float_tensor1 = torch.tensor([1, 2, 3], dtype=torch.float)
float_tensor2 = torch.tensor([4, 5, 6], dtype=torch.float32)
float_tensor3 = torch.FloatTensor([7, 8, 9])  # Legacy Constructors

for tensor in [float_tensor1, float_tensor2, float_tensor3]:
    print(f"{tensor}'s element data type is {tensor.dtype}")

tensor([1., 2., 3.])'s element data type is torch.float32
tensor([4., 5., 6.])'s element data type is torch.float32
tensor([7., 8., 9.])'s element data type is torch.float32


In [162]:
# 32-bit floating point
print(torch.float)
# 32-bit integer (signed)
print(torch.int)
# Boolean
print(torch.bool)

# 64-bit floating point
print(torch.double)
# 64-bit inteber (signed)
print(torch.long)

torch.float32
torch.int32
torch.bool
torch.float64
torch.int64


In [165]:
torch.tensor([1, 2, 3]).dtype

torch.int64

### `device`   
* `cpu`   
* `gpu`   

In [167]:
cpu_tensor = torch.tensor([1, 2, 3])
gpu_tensor1 = torch.tensor([4, 5, 6], device="cuda")
gpu_tensor2 = torch.tensor([7, 8, 9], device=torch.device("cuda"))

for tensor in [cpu_tensor, gpu_tensor1, gpu_tensor2]:
    print(f"{tensor}'s device is {tensor.device}")

tensor([1, 2, 3])'s device is cpu
tensor([4, 5, 6], device='cuda:0')'s device is cuda:0
tensor([7, 8, 9], device='cuda:0')'s device is cuda:0


In [179]:
available_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(available_device)

cuda


### `layout`   
`torch.sparse_coo`는 베타 버전, 바뀔 수 있음
* `torch.strided`: Dense Tensor   
* `torch.sparse_coo`: Sparse Tensor   

## 연산

### inplace

In [4]:
data = torch.zeros(2, 3)
print("===Before===")
print(data)
data.add_(12)
print("===After===")
print(data)

===Before===
tensor([[0., 0., 0.],
        [0., 0., 0.]])
===After===
tensor([[12., 12., 12.],
        [12., 12., 12.]])


### Reshape
```view```  
같은 데이터를 공유한다. (shallow copy)

```reshape```   
Copying과 viewing이 되는 상황을 구분하는 것이 의미 없다.    
> but you should not depend on the copying vs. viewing behavior.

```contiguous```    


### Dimension swap
```transpose```   
```permute```   

### Flatten할 때
```ravel```   
```flatten```   

### Concatenate   
```cat```   
```stack```   