In [49]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [50]:
torch.from_numpy(np.array(data))

tensor([[1, 2],
        [3, 4]])

In [51]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [52]:
torch.zeros_like(x_data)

tensor([[0, 0],
        [0, 0]])

In [53]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.8168, 0.8440],
        [0.9319, 0.8063]])

In [54]:
shape = (2, 3)
print(torch.rand(shape))
print(torch.ones(shape))
print(torch.zeros(shape))

tensor([[0.1022, 0.2463, 0.7079],
        [0.6383, 0.4505, 0.1758]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [55]:
x_data.to("cuda")

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [56]:
torch.tensor(data, device="cuda")

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [57]:
x_cube = torch.tensor([[[1, 2], [3, 4]], [[5,6],[7,8]]])
print(x_cube)
print(x_cube[0])
print(x_cube[:, 0, :])
print(x_cube[..., 0])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [5, 6]])
tensor([[1, 3],
        [5, 7]])


In [58]:
torch.cat([x_data, x_data], dim=1)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [59]:
print(x_data @ x_data)
print(x_data.matmul(x_data))

tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [60]:
print(x_data * x_data)
print(x_data.mul(x_data))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [61]:
print(x_data.sum())

tensor(10)


In [62]:
x_data.add_(-1)

tensor([[0, 1],
        [2, 3]])

In [63]:
x_np = np.array([[1, 2], [3, 4]])
x_tensor = torch.from_numpy(x_np)
x_tensor

tensor([[1, 2],
        [3, 4]])

In [64]:
torch.tensor(x_np)

tensor([[1, 2],
        [3, 4]])

In [65]:
x_tensor.numpy()

array([[1, 2],
       [3, 4]])

In [66]:
x_tensor.add_(1)
print(x_tensor)
print(x_np)

tensor([[2, 3],
        [4, 5]])
[[2 3]
 [4 5]]
