In [9]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
torch.from_numpy(np.array(data))

tensor([[1, 2],
        [3, 4]])

In [11]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [13]:
torch.zeros_like(x_data)

tensor([[0, 0],
        [0, 0]])

In [24]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.7413, 0.2122],
        [0.3709, 0.1521]])

In [26]:
shape = (2, 3)
print(torch.rand(shape))
print(torch.ones(shape))
print(torch.zeros(shape))

tensor([[0.0047, 0.4148, 0.3974],
        [0.1425, 0.1159, 0.4525]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
